.segment Code [outBin="main.crt", allowOverlap]

//Initialise cart
#define D64	//Valid values D64, MAGICDESK, GMOD2
.var CART_ZP_START = $e8 //10 bytes min
.var CART_COPY_BASE = $0400	//For D64 must be loadraw from loadersymbols-c64.inc
.var CART_MAX_FILES = 256 
.var KRILL_INSTALL_METHOD = $10dd //D64 only, Found in loadersymbols-c64.inc
#import "./loader/cartLoader.asm"

 

#if D64
	////////////////////////////////////
	//Add disk boot and directory here
	////////////////////////////////////
	.disk [filename="LoaderDemo.d64", name="TEST LOADER"] {
		[name="TESTLOADER",		type="prg",	segments="DISK_BOOT"],	//Always first segment, generated by CreateDiskBoot
		[name="TEST",			type="prg",	segments="TEST"],	
		[name="TEST2",			type="prg",	segments="TEST2"]
	}

	LOADER_CreateDiskBoot("TEST", $0900)
#else 
	////////////////////////////////////
	//Add cart filesystem here
	////////////////////////////////////
	
	LOADER_AddFile("TEST", TEST, __TEST, $0900) //First file will auto load
	LOADER_AddFile("TEST2", TEST2, __TEST2, $0a00)
#endif
	
 


//FILES
#if D64 
.segment TEST [start=$0900] 
#endif
TEST:	
	.pseudopc $0900 {
			LOADER_LoadFile("TEST2")
			jmp Entry
	}
__TEST:





#if D64 
.segment TEST2 [start=$0a00]
#endif
TEST2:
	.pseudopc $0a00 {
			.fill $f280, $ee
		Entry:
		!:
			inc $d020
			jmp !-
	}
__TEST2:
